### ISSUE TITLE
Hi could you please give me some info on how to populate the .env file.

### ISSUE THREAD

**Issue by Dewtah** [cenk1cenk2/docker-softether-vpnsrv#29]
I have tried a lot, but when using docker compose, it first says that the .env file is missing. When creating one (which with i thought default vars) it doesn't seem to be recognized by the build process of the container.
So I suppose my syntax inside the .env file is with a wrong syntax.
I have tried:
LINUX_BRIDGE_INTERFACE_NAME="bridge"

$LINUX_BRIDGE_INTERFACE_NAME="bridge"

LINUX_BRIDGE_INTERFACE_NAME "bridge"

Is it perhaps json syntax?
If so what are its dict/array names

And all sorts of combo's
Then I noticed it get loaded with pipe from golang. 
Which you have another repo for.
So the questions also arose if I needed to install or do something with that.

Edit: No json doesn't get parsed all 

Anyway's a little help would be much appreciated.

**Comment by cenk1cenk2** [comment]
Hey @Dewtah,

No worries. Will try to explain it further on.

The `docker-compose.yml` file on the root of the repository is mostly for testing and demonstration purposes, you can use the `latest` version from DockerHub instead of actually building it.

```yml
version: '3.7'
services:
  softether-vpnsrv:
    image: cenk1cenk2/softether-vpnsrv:latest
    env_file: .env
    devices:
      - /dev/net/tun
    ports:
      - 1443:1443/tcp
      - 992:992/tcp
      - 5555:5555/tcp
      - 1194:1194/udp
      - 500:500/udp
      - 4500:4500/udp
      - 1701:1701/tcp
    network_mode: bridge
    volumes:
      # Configuration Files
      - ./volumes/softether-vpnsrv:/conf
      # Log files
      - ./logs/server_log:/etc/softether/server_log
      - ./logs/security_log:/etc/softether/security_log
      - ./logs/packet_log:/etc/softether/packet_log
    cap_add:
      - SETGID
      - SETUID
      - NET_ADMIN
      - NET_RAW
      - NET_BIND_SERVICE
```

For the second part of it you can either create a environment variable file and indicate that the docker-compose stack should run with it as in the example like `env_file: ./.env` or you can also use the `environment` key inside the docker-compose specification.

`$` sign in the front is just to indicate that it is an environment variable, since the documentation is autogenerated from the CLI flags where it can also have CLI flags like `--something`.

So to sumarize you can do:
```yml
version: '3.7'
services:
  softether-vpnsrv:
    image: cenk1cenk2/softether-vpnsrv:latest
    environment:
      LINUX_BRIDGE_INTERFACE_NAME: 'bridge'
    devices:
      - /dev/net/tun
    ports:
      - 1443:1443/tcp
      - 992:992/tcp
      - 5555:5555/tcp
      - 1194:1194/udp
      - 500:500/udp
      - 4500:4500/udp
      - 1701:1701/tcp
    network_mode: bridge
    volumes:
      # Configuration Files
      - ./volumes/softether-vpnsrv:/conf
      # Log files
      - ./logs/server_log:/etc/softether/server_log
      - ./logs/security_log:/etc/softether/security_log
      - ./logs/packet_log:/etc/softether/packet_log
    cap_add:
      - SETGID
      - SETUID
      - NET_ADMIN
      - NET_RAW
      - NET_BIND_SERVICE
```
