### ISSUE TITLE
Connection no network

### ISSUE THREAD

**Issue by 775118134** [cenk1cenk2/docker-softether-vpnsrv#42]
hi~
Cloud host:  
![image](https://github.com/cenk1cenk2/docker-softether-vpnsrv/assets/10275524/fc8322fd-6451-4529-8ad8-53ecfa64d0cb)
![image](https://github.com/cenk1cenk2/docker-softether-vpnsrv/assets/10275524/f2d2fe07-c7cd-4fb4-8d8b-fa25715e4569)
![image](https://github.com/cenk1cenk2/docker-softether-vpnsrv/assets/10275524/6eaa4d92-f47c-4b75-a108-755c376a2f0b)

in container：
![image](https://github.com/cenk1cenk2/docker-softether-vpnsrv/assets/10275524/1877aa6b-4bd4-47e7-9b15-b0aeb70077bb)
![image](https://github.com/cenk1cenk2/docker-softether-vpnsrv/assets/10275524/69fee22b-b843-4aa0-b597-3622831889eb)

Cloud host: 
> 192.168.0.36

docker container softether ：
> eth0 172.20.30.2
> tap_soft 192.168.32.1

remote vpn client
> ![image](https://github.com/cenk1cenk2/docker-softether-vpnsrv/assets/10275524/94fa1410-c65a-4bba-93ab-1ff24370bad0)
> ![image](https://github.com/cenk1cenk2/docker-softether-vpnsrv/assets/10275524/94416798-7c25-4079-b938-c08d02b966cf)
> ![image](https://github.com/cenk1cenk2/docker-softether-vpnsrv/assets/10275524/ee244648-e072-437d-b70e-9164a0a0a9f4)

docker-compose.yml
```
version: '3'
services:
  softether:
    image: cenk1cenk2/softether-vpnsrv:latest
    container_name: softether
    restart: always
    networks:
      soft_network:
        ipv4_address: 172.20.30.2
    devices:
      - /dev/net/tun
    environment:
      - TZ=Asia/Shanghai
      - LOG_LEVEL=trace
      - SERVER_MODE=dhcp
      - SERVER_CIDR_ADDRESS=192.168.32.0/24
      - DHCP_SERVER_LEASE=12h
      - DHCP_SERVER_SEND_GATEWAY=true
      - DHCP_SERVER_GATEWAY=192.168.32.1
      - DHCP_SERVER_FORWARDING_ZONE=127.0.0.11
      - SOFTETHER_TAP_INTERFACE=soft
      - SOFTETHER_DEFAULT_HUB=VPN
    ports:
      - 443:1443/tcp     # softether
      - 992:992/tcp       # softether alternative
      - 5555:5555/tcp     # softether alternative
      - 1194:1194/udp     # openvpn
      - 500:500/udp       # l2tp IPSec IKE
      - 4500:4500/udp     # l2tp IPSec
      - 1701:1701/tcp     # l2tp
    volumes:
      - ./conf:/conf
      - ./hooks:/docker.init.d:ro
      - ./server_log:/etc/softether/server_log
      - ./security_log:/etc/softether/security_log
      - ./packet_log:/etc/softether/packet_log
    cap_add:
      - SETGID
      - SETUID
      - NET_ADMIN
      - NET_RAW
      - NET_BIND_SERVICE
networks:
  soft_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.30.0/24
          gateway: 172.20.30.1
```
dnsmasq.conf
```
# Comment out the port=0 so dnsmasq can provide dns services to clients
# port=0
interface=tap_soft
dhcp-range=tap_soft,192.168.32.10,192.168.32.200,255.255.255.0,12h
dhcp-option=tap_soft,3,192.168.32.1
# set option 6 to announce itself as the DNS server
dhcp-option=tap_soft,6,192.168.32.1
# Use option 121 to announce to *nix vpn clients various routes you want routed through the VPN to allow split tunnel
dhcp-option=tap_soft,121,192.168.0.0/24,192.168.32.1,192.168.10.0/24,192.168.32.1
# use option 249 to announce to windows vpn clients the same routes as 121
dhcp-option=tap_soft,249,192.168.0.0/24,192.168.32.1,192.168.10.0/24,192.168.32.1
# Send microsoft-specific option to tell windows to release the DHCP lease
# when it shuts down. Note the "i" flag, to tell dnsmasq to send the
# value as a four-byte integer - that's what microsoft wants. See
# https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dhcpe/4cde5ceb-4fc1-4f9a-82e9-13f6b38d930c
dhcp-option=vendor:MSFT,2,1i

conf-dir=/etc/dnsmasq.d
```

runtime log:
![image](https://github.com/cenk1cenk2/docker-softether-vpnsrv/assets/10275524/f4f83cae-cec4-481a-8e3f-93f03f1c36f7)

The docker docker-softether-vpnsrv container 172.20.30.2 is deployed on the cloud host 192.168.0.36, and the 1443 port is connected through the softether client ssl protocol. It is now connected and assigned the IP address 192.168.32.53, but it can only communicate with the container 172.20. 30.2 Communication, I cannot access the host, LAN, or Internet. Can you help me see how to modify it?
